import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test')
    .default('development'),
  PORT: Joi.number().port().default(3000),
  DB_HOST: Joi.string().default('localhost'),
  DB_PORT: Joi.number().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_ACCESS_EXPIRATION: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRATION: Joi.string().default('7d'),
  CONFIRMATION_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  PASSWORD_RESET_TOKEN_EXPIRATION_HOURS: Joi.number().default(1),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  MAIL_HOST: Joi.string().default('mailpit'),
  MAIL_PORT: Joi.number().default(1025),
  MAIL_FROM: Joi.string().default('"StreamTube" <noreply@streamtube.com>'),
  SWAGGER_ENABLED: Joi.string().valid('true', 'false').default('false'),
  S3_ENDPOINT: Joi.string().uri().default('http://minio:9000'),
  S3_PUBLIC_ENDPOINT: Joi.string().uri().default('http://localhost:9000'),
  S3_REGION: Joi.string().default('us-east-1'),
  S3_BUCKET: Joi.string().required(),
  S3_ACCESS_KEY_ID: Joi.string().required(),
  S3_SECRET_ACCESS_KEY: Joi.string().required(),
  S3_FORCE_PATH_STYLE: Joi.string().valid('true', 'false').default('true'),
  PRESIGNED_URL_EXPIRATION_SECONDS: Joi.number().default(900),
  S3_CORS_ALLOW_ORIGIN: Joi.string().default('http://localhost:3001'),
  QUEUE_SCHEMA: Joi.string().default('pgboss'),
  QUEUE_RETRY_LIMIT: Joi.number().default(3),
  QUEUE_EXPIRE_IN_SECONDS: Joi.number().default(3600),
  UPLOAD_MAX_SIZE_BYTES: Joi.number().default(10737418240),
  UPLOAD_ACCEPTED_CONTAINERS: Joi.string().default('mp4,mov,webm,mkv'),
  UPLOAD_ACCEPTED_VIDEO_CODECS: Joi.string().default('h264,vp9,av1'),
  UPLOAD_ABANDONED_EXPIRATION_HOURS: Joi.number().default(24),
  UPLOAD_TICKET_EXPIRATION_HOURS: Joi.number().default(2),
  UPLOAD_PART_SIZE_BYTES: Joi.number().default(8388608),
  UPLOAD_PUBLIC_URL: Joi.string()
    .uri()
    .default('http://localhost:3000/uploads'),
  FFMPEG_TIMEOUT_SECONDS: Joi.number().default(3600),
  THUMBNAIL_OFFSET_PERCENT: Joi.number().min(0).max(100).default(10),
  WORKER_SCRATCH_DIR: Joi.string().default('/tmp/streamtube'),
  WORKER_CONCURRENCY: Joi.number().min(1).default(1),
  UPLOAD_SWEEP_CRON: Joi.string().default('0 * * * *'),
});
